package com.performance.persist.domain;

public class ScientificResearch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scientific_research.id
     *
     * @mbggenerated
     */
    private Long virtualId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scientific_research.sci_content
     *
     * @mbggenerated
     */
    private String sciContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scientific_research.sci_project
     *
     * @mbggenerated
     */
    private String sciProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scientific_research.sci_grade
     *
     * @mbggenerated
     */
    private String sciGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scientific_research.sci_score
     *
     * @mbggenerated
     */
    private Integer sciScore;

    /**
     * This field corresponds to the database column scientific_research.status
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scientific_research.id
     *
     * @return the value of scientific_research.id
     *
     * @mbggenerated
     */
    public Long getVirtualId() {
        return virtualId;
    }

    /**
     * This method sets the value of the database column scientific_research.id
     * @param id the value for scientific_research.id
     */
    public void setVirtualId(Long virtualId) {
        this.virtualId = virtualId;
    }

    public String getSciContent() {
        return sciContent;
    }

    public void setSciContent(String sciContent) {
        this.sciContent = sciContent == null ? null : sciContent.trim();
    }

    public String getSciProject() {
        return sciProject;
    }

    public void setSciProject(String sciProject) {
        this.sciProject = sciProject == null ? null : sciProject.trim();
    }

    public String getSciGrade() {
        return sciGrade;
    }

    public void setSciGrade(String sciGrade) {
        this.sciGrade = sciGrade == null ? null : sciGrade.trim();
    }

    public Integer getSciScore() {
        return sciScore;
    }

    public void setSciScore(Integer sciScore) {
        this.sciScore = sciScore;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}