package com.performance.persist.domain;

public class TeacherPerformance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_performance.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_performance.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_performance.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_performance.project
     *
     * @mbggenerated
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_performance.pro_grade
     *
     * @mbggenerated
     */
    private String proGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_performance.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_performance.id
     *
     * @return the value of teacher_performance.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_performance.id
     *
     * @param id the value for teacher_performance.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_performance.category
     *
     * @return the value of teacher_performance.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_performance.category
     *
     * @param category the value for teacher_performance.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_performance.content
     *
     * @return the value of teacher_performance.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_performance.content
     *
     * @param content the value for teacher_performance.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_performance.project
     *
     * @return the value of teacher_performance.project
     *
     * @mbggenerated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_performance.project
     *
     * @param project the value for teacher_performance.project
     *
     * @mbggenerated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_performance.pro_grade
     *
     * @return the value of teacher_performance.pro_grade
     *
     * @mbggenerated
     */
    public String getProGrade() {
        return proGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_performance.pro_grade
     *
     * @param proGrade the value for teacher_performance.pro_grade
     *
     * @mbggenerated
     */
    public void setProGrade(String proGrade) {
        this.proGrade = proGrade == null ? null : proGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_performance.status
     *
     * @return the value of teacher_performance.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_performance.status
     *
     * @param status the value for teacher_performance.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}